name: Bug
description: Something Knot did incorrectly
labels: ["bug"]
body:
  - type: textarea
    id: expected
    attributes:
      label: Expected
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Knot version
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction
    validations:
      required: true
